package com.benner.regulador;
import java.util.Map;
import java.util.HashMap;
import org.jbpm.casemgmt.api.CaseService;
import org.jbpm.casemgmt.api.model.instance.CaseFileInstance;
import org.jbpm.document.Document;
import org.jbpm.services.api.service.ServiceRegistry;
import org.kie.api.runtime.process.CaseData;
import org.kie.api.runtime.process.WorkflowProcessInstance;



rule "Testando o case file em drl"
    ruleflow-group "rgr:Regulador.Starting"
    dialect "mvel"
    no-loop true
    when
    	$processInstance: WorkflowProcessInstance()
        $caseData : CaseFileInstance()
        //$controle : controle()
        //Document(name == "invalid.pdf") from $caseData.getData("hwSpec")
       $controle: controle() from $caseData.getData("controle")
       $solicitante: solicitante() from $caseData.getData("solicitante")
        
    then
    	System.out.println("REGULACAO starting...");
        System.out.println("\t"+$caseData.getCaseId());
        //System.out.println($caseData.getData());
        System.out.println("\tINPUT DESCRICAO:"+$controle.getNome());
        //System.out.println("\tINPUT EMAIL:"+$solicitante.getSolicitanteEmail());
        System.out.println("\tINPUT EMAIL:"+ $caseData.getData("emailTo"));
        
        System.out.println("\tSOLICITANTE:");
        System.out.println("\t\tNOME:"+ $solicitante.getNome());
        System.out.println("\t\tEMAIL:"+ $solicitante.getSolicitanteEmail());


        WorkflowProcessInstance $p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance($processInstance.getId()); //casting to WorkflowProcessInstance is essential
        
        $p.setVariable("caseFile_emailTo","luiza.garcia@triopropaganda.com");;
        
    
        $solicitante.setNome("CLINICA CARLOS GOMES")
        $solicitante.setSolicitanteEmail("contato@clinicacarlosgomes.com.br")

        System.out.println("\tSOLICITANTE ALTERADO:");
        System.out.println("\t\tNOME:"+ $solicitante.getNome());
        System.out.println("\t\tEMAIL:"+ $solicitante.getSolicitanteEmail());


        System.out.println("\tOUTPUT EMAIL:"+ $caseData.getData("emailTo"));
        
        retract($processInstance);
end

rule "Closing the case"
    ruleflow-group "rgr:Regulador.Close"
    dialect "mvel"
    no-loop true
    when
        $caseData : CaseFileInstance()
    then
        System.out.println("###FECHANDO O CASO:"+$caseData.getCaseId);
        //closeCase(String caseId, String comment) throws CaseNotFoundException;
        //CaseService caseService = (CaseService) ServiceRegistry.get().service(ServiceRegistry.CASE_SERVICE);
        //CaseService.closeCase($caseData.getCaseId,"CLOSED")
end
        
