package com.benner.regulador;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class controle implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String situacaoANS;
	private java.lang.Boolean negativaBeneficiario;
	private java.lang.Boolean negativaPrestador;

	private java.lang.String descricao;

	public controle() {
	}

	public java.lang.String getSituacaoANS() {
		return this.situacaoANS;
	}

	public void setSituacaoANS(java.lang.String situacaoANS) {
		this.situacaoANS = situacaoANS;
	}

	public java.lang.Boolean getNegativaBeneficiario() {
		return this.negativaBeneficiario;
	}

	public void setNegativaBeneficiario(java.lang.Boolean negativaBeneficiario) {
		this.negativaBeneficiario = negativaBeneficiario;
	}

	public java.lang.Boolean getNegativaPrestador() {
		return this.negativaPrestador;
	}

	public void setNegativaPrestador(java.lang.Boolean negativaPrestador) {
		this.negativaPrestador = negativaPrestador;
	}

	public java.lang.String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(java.lang.String descricao) {
		this.descricao = descricao;
	}

	public controle(java.lang.String situacaoANS,
			java.lang.Boolean negativaBeneficiario,
			java.lang.Boolean negativaPrestador, java.lang.String descricao) {
		this.situacaoANS = situacaoANS;
		this.negativaBeneficiario = negativaBeneficiario;
		this.negativaPrestador = negativaPrestador;
		this.descricao = descricao;
	}

}