package com.benner.regulador;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class solicitante implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Nome")
	private java.lang.String nome;
	@org.kie.api.definition.type.Label(value = "Email")
	private java.lang.String solicitanteEmail;

	public solicitante() {
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.String getSolicitanteEmail() {
		return this.solicitanteEmail;
	}

	public void setSolicitanteEmail(java.lang.String solicitanteEmail) {
		this.solicitanteEmail = solicitanteEmail;
	}

	public solicitante(java.lang.String nome, java.lang.String solicitanteEmail) {
		this.nome = nome;
		this.solicitanteEmail = solicitanteEmail;
	}

}